version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  graph-mock:
    image: python:3.11-slim
    command: python -m http.server 8001
    ports:
      - "8001:8001"
  messaging-mock:
    image: python:3.11-slim
    command: python -m http.server 8002
    ports:
      - "8002:8002"
volumes:
  pgdata: 